name: Web Pages

on:
  # 触发条件：当 main 分支有代码提交（或你在网页上改了内容）时，立刻自动运行
  push:
    branches: ["main"]

  # 允许你在 Actions 界面手动点击按钮强制触发
  workflow_dispatch:

# 设置权限，允许这个脚本读取代码并写入到 Pages 服务器
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署任务在运行，防止冲突
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-size: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages Environment
        uses: actions/configure-pages@v5

      - name: Upload Entire Folder Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 托管当前仓库的根目录（即包含 index.html 的地方）
          path: '.'

      - name: Deploy to GitHub Pages Server
        id: deployment
        uses: actions/deploy-pages@v4
